language: python
python:
  - "3.6"
  - "3.7-dev"


install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  - echo 0

after_success:
  - codecov

deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: your-moodle
